
name: Deploy Django App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          procfile: "web: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "my-blogger12"
          heroku_email: ${{ secrets.EMAIL }}
          healthcheck: "https://my-blogger12.herokuapp.com/healthy/"